# The recommended basic settings for GNN
out_dir: results
train:
  batch_size: 32
  eval_period: 20
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 2
  layers_mp: 6
  layers_post_mp: 2
  dim_inner: 256
  layer_type: generalconv
  stage_type: skipsum
  batchnorm: True
  act: prelu
  dropout: 0.0
  agg: max
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 400